name: saasify
description: This ERP software integrates HR, POS, and Accounting modules to streamline business processes. Manage employee data, automate sales transactions, and handle accounting seamlessly for enhanced organizational efficiency.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  pdf: ^3.10.8
  intl: ^0.19.0
  hive: ^2.2.3
  get_it: ^7.6.7
  equatable: ^2.0.5
  dotted_line: ^3.2.2
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  flutter_bloc: ^8.1.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.25.4
  cloud_firestore:
  cupertino_icons: ^1.0.6
  firebase_storage: ^11.6.10
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.15



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  hive_generator: ^1.1.1
  build_runner: ^2.0.5

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: PT_Sans
      fonts:
        - asset: assets/fonts/PT_Sans/PTSans-Bold.ttf
        - asset: assets/fonts/PT_Sans/PTSans-Regular.ttf
