name: Deploy to production ğŸš€

on:
  push:
    branches: [ "master", "dev", "uat" ]

jobs:

  build:
    name: ğŸ‘· Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3
      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: ğŸ‘¨â€âš•ï¸ Flutter doctor
        run: flutter doctor

      - name: ğŸ–¥ï¸ Flutter dependencies
        run: flutter pub get

      - name: ğŸ‘® Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: ğŸ” Analyze project source
        run: dart analyze

      - name: ğŸ› ï¸ Build the application
        run: flutter build web

      - name: â¬‡ï¸ Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/web

  deploy:
    name: ğŸ›« Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ğŸ“š Checkout repo
        uses: actions/checkout@v3
      - name: â¬‡ï¸ Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/web
      - name: ğŸ¯ Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.PROD_FIREBASE_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"
          channelId: live
          projectId: saasify-production
